using System;
using System.Collections.Generic;
using System.Text;

namespace Dlrsoft.VBScript.Runtime
{
    class BuiltInConstants
    {
        public const int vbUseSystem = 0;
        public const int vbUseSystemDayOfWeek = 0;
        public const int vbSunday = 1;
        public const int vbMonday = 2;
        public const int vbTuesday = 3;
        public const int vbWednesday = 4;
        public const int vbThursday = 5;
        public const int vbFriday = 6;
        public const int vbSaturday = 7;
        public const int vbFirstJan1 = 1;
        public const int vbFirstFourDays = 2;
        public const int vbFirstFullWeek = 3;
        public const int vbOKOnly = 0;
        public const int vbOKCancel = 1;
        public const int vbAbortRetryIgnore = 2;
        public const int vbYesNoCancel = 3;
        public const int vbYesNo = 4;
        public const int vbRetryCancel = 5;
        public const int vbCritical = 16;
        public const int vbQuestion = 32;
        public const int vbExclamation = 48;
        public const int vbInformation = 64;
        public const int vbDefaultButton1 = 0;
        public const int vbDefaultButton2 = 256;
        public const int vbDefaultButton3 = 512;
        public const int vbDefaultButton4 = 768;
        public const int vbApplicationModal = 0;
        public const int vbSystemModal = 4096;
        public const int vbOK = 1;
        public const int vbCancel = 2;
        public const int vbAbort = 3;
        public const int vbRetry = 4;
        public const int vbIgnore = 5;
        public const int vbYes = 6;
        public const int vbNo = 7;
        public const int vbEmpty = 0;
        public const int vbNull = 1;
        public const int vbInteger = 2;
        public const int vbLong = 3;
        public const int vbSingle = 4;
        public const int vbDouble = 5;
        public const int vbCurrency = 6;
        public const int vbDate = 7;
        public const int vbString = 8;
        public const int vbObject = 9;
        public const int vbError = 10;
        public const int vbBoolean = 11;
        public const int vbVariant = 12;
        public const int vbDataObject = 13;
        public const int vbDecimal = 14;
        public const int vbByte = 17;
        public const int vbArray = 8192;
        public const bool vbTrue = true;
        public const bool vbFalse = false;
        public const int vbUseDefault = -2;
        public const int vbBinaryCompare = 0;
        public const int vbTextCompare = 1;
        public const int vbDatabaseCompare = 2;
        public const int vbGeneralDate = 0;
        public const int vbLongDate = 1;
        public const int vbShortDate = 2;
        public const int vbLongTime = 3;
        public const int vbShortTime = 4;
        public const int vbObjectError = -2147221504;
        public const int vbBlack = 0x00;
        public const int vbBlue = 0xFF;
        public const int vbCyan = 0xFFFF00;
        public const int vbGreen = 0xFF00;
        public const int vbMagenta = 0xFF00FF;
        public const int vbRed = 0xFF;
        public const int vbWhite = 0xFFFFFF;
        public const int vbYellow = 0xFFFF;
        public const string vbCr = "\r";
        public const string vbCrLf = "\r\n";
        public const string vbNewLine = "\r\n";
        public const string vbFormFeed = "\u0012";
        public const string vbLf = "\n";
        public const string vbNullChar = "\u0000";
        public const string vbNullString = "";
        public const string vbTab = "\t";
        public const string vbVerticalTab = "\u0011";
        public const int vbMsgBoxHelpButton = 0x4000;
        public const int VbMsgBoxSetForeground = 0x10000;
        public const int vbMsgBoxRight = 0x80000;
        public const int vbMsgBoxRtlReading = 0x100000;
    }
}
